repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.263'
    hooks:
      - id: ruff 
        name: ruff - linter
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
        name: pyupgrade - upgrade python syntax

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        name: mypy - optional static type checker

  - repo: local
    hooks:
      - id: pytest
        name:  pytest - unit tests
        entry: pipenv run pytest tests --disable-warnings
        stages: [commit]
        types: [python]
        language: system
        pass_filenames: false
        always_run: true
