# Use this compose only for local development
version: '3.3'
services:
    app:
        build: .
        container_name: libraryapi
        command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
        ports:
            - '8000:80'
        image: libraryapi:latest
        volumes:
            - .:/app
