[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.poetry]
name = "libraryapi"
version = "1.0.0"
description = "An API to get MARC data from Pergamum."
authors = ["Vítor <vitor.silverio.rodrigues@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "==0.111.0"
pymarc = "==5.1.2"
uvicorn = {version = "==0.30.0", extras = ["standard"]}
xmltodict = "==0.13.0"
zeep = {version = "==4.2.1", extras = ["async"]}
httpx = "==0.27.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "==3.7.1"
pytest = "==8.2.1"
pipenv = "==2023.12.1"
ruff = "*"
mypy = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
